Repository mlynch5187/monster_shop_2001, pull requests merged in 2020-04, with the labels that each got.

#1 User reg
  app/controllers/merchants_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20200406203320_create_users.rb
  db/schema.rb
  spec/features/user_registrations/new_user_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#2 Navigation branch
  app/controllers/admin/dashboard_controller.rb
  app/controllers/application_controller.rb
  app/controllers/cart_controller.rb
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/merchants_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/profile_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/welcome_controller.rb
  app/models/user.rb
  app/views/admin/index.html.erb
  app/views/layouts/application.html.erb
  app/views/profile/index.html.erb
  app/views/sessions/new
  app/views/welcome/index.html.erb
  config/routes.rb
  db/migrate/20200407215930_add_role_to_user.rb
  db/schema.rb
  spec/features/navigation_spec.rb
  spec/features/users/index_spec.rb
Labels: enhancement

#3 User Login Implementation (User Stories 13-16)
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/controllers/application_controller.rb
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/admin/dashboard/index.html.erb
  app/views/layouts/application.html.erb
  app/views/merchant/dashboard/index.html.erb
  app/views/profile/index.html.erb
  app/views/sessions/new
  app/views/sessions/new.html.erb
  app/views/users/new.html.erb
  config/routes.rb
  spec/features/sessions/destroy_spec.rb
  spec/features/sessions/new_spec.rb
  spec/features/user_registrations/new_user_spec.rb
  spec/features/users/index_spec.rb
Labels: enhancement

#4 User profile
  app/controllers/passwords_controller.rb
  app/controllers/profile_controller.rb
  app/models/user.rb
  app/views/passwords/edit.html.erb
  app/views/profile/edit.html.erb
  app/views/profile/index.html.erb
  config/routes.rb
  spec/features/profile/show_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#6 Cart branch
  app/controllers/cart_controller.rb
  app/models/cart.rb
  app/views/cart/show.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/features/cart/show_spec.rb
Labels: enhancement

#7 Cart branch 2
  app/controllers/orders_controller.rb
  app/models/order.rb
  app/models/user.rb
  app/views/orders/index.html.erb
  config/routes.rb
  db/migrate/20200411183144_add_users_to_orders.rb
  db/schema.rb
  spec/features/cart/checkout_spec.rb
  spec/features/items/destroy_spec.rb
  spec/features/items/index_spec.rb
  spec/features/merchants/destroy_spec.rb
  spec/features/merchants/statistics_spec.rb
  spec/features/orders/creation_spec.rb
  spec/features/orders/new_spec.rb
  spec/features/profile/show_spec.rb
  spec/models/item_orders_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/order_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#8 Clean up US 1 -22
  app/assets/stylesheets/application.css
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/passwords_controller.rb
  app/controllers/profile/orders_controller.rb
  app/controllers/profile_controller.rb
  app/controllers/sessions_controller.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/profile/index.html.erb
  app/views/profile/orders/index.html.erb
  app/views/sessions/new.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/profile/show_spec.rb
  spec/features/users/index_spec.rb
  spec/models/merchant_spec.rb
Labels: refactor

#10 Admin orders
  app/controllers/admin/dashboard_controller.rb
  app/controllers/admin/orders_controller.rb
  app/controllers/admin/profile_controller.rb
  app/controllers/item_orders_controller.rb
  app/models/order.rb
  app/views/admin/dashboard/index.html.erb
  app/views/admin/profile/show.html.erb
  app/views/item_orders/show.html.erb
  app/views/profile/orders/show.html.erb
  config/routes.rb
  spec/features/admin/orders/show_spec.rb
  spec/features/orders/order_updates_spec.rb
  spec/features/profile/orders/show_spec.rb
  spec/models/order_spec.rb
Labels: enhancement

#14 Merchant index
  app/controllers/admin/merchants_controller.rb
  app/views/admin/merchants/index.html.erb
  config/routes.rb
  db/migrate/20200413175921_add_active_to_merchants.rb
  db/schema.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/admin/orders/show_spec.rb
  spec/features/merchants/dashboard/show_spec.rb
  spec/features/sessions/new_spec.rb
Labels: enhancement

#15 Merchant Employee - Items CRUD (US 42 - 48)
  app/assets/stylesheets/application.css
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/merchant/items_controller.rb
  app/controllers/profile_controller.rb
  app/models/item.rb
  app/models/merchant.rb
  app/views/admin/merchants/show.html.erb
  app/views/items/index.html.erb
  app/views/merchant/dashboard/index.html.erb
  app/views/merchant/items/edit.html.erb
  app/views/merchant/items/index.html.erb
  app/views/merchant/items/new.html.erb
  config/routes.rb
  db/seeds.rb
  spec/features/items/edit_spec.rb
  spec/features/merchant/items/create_spec.rb
  spec/features/merchant/items/destroy_spec.rb
  spec/features/merchant/items/edit_spec.rb
  spec/features/merchant/items/update_spec.rb
  spec/features/merchants/dashboard/show_spec.rb
  spec/features/sessions/new_spec.rb
  spec/models/item_spec.rb
  spec/models/order_spec.rb
Labels: enhancement

#17 Merchant fulfillment branch
  app/controllers/item_orders_controller.rb
  app/controllers/merchant/orders_controller.rb
  app/models/item.rb
  app/models/merchant.rb
  app/models/order.rb
  app/views/merchant/items/index.html.erb
  app/views/merchant/orders/show.html.erb
  config/routes.rb
  spec/features/merchants/orders/show_spec.rb
Labels: enhancement

#18 Partials refactor
  app/controllers/admin/dashboard_controller.rb
  app/controllers/admin/merchants_controller.rb
  app/controllers/admin/orders_controller.rb
  app/controllers/admin/profile_controller.rb
  app/controllers/application_controller.rb
  app/controllers/cart_controller.rb
  app/controllers/items_controller.rb
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/merchant/items_controller.rb
  app/controllers/merchant/orders_controller.rb
  app/controllers/merchants_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/passwords_controller.rb
  app/controllers/profile/orders_controller.rb
  app/controllers/profile_controller.rb
  app/controllers/reviews_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/controllers/welcome_controller.rb
  app/models/cart.rb
  app/models/item.rb
  app/models/item_order.rb
  app/models/merchant.rb
  app/models/order.rb
  app/models/review.rb
  app/views/admin/dashboard/index.html.erb
  app/views/admin/merchants/index.html.erb
  app/views/admin/merchants/show.html.erb
  app/views/admin/profile/index.html.erb
  app/views/admin/profile/show.html.erb
  app/views/layouts/application.html.erb
  app/views/merchant/_pending_orders.html.erb
  app/views/merchant/dashboard/index.html.erb
  app/views/merchant/items/index.html.erb
  app/views/merchant/orders/show.html.erb
  app/views/merchants/_merchants_address.html.erb
  app/views/merchants/_merchants_index.html.erb
  app/views/merchants/index.html.erb
  app/views/merchants/show.html.erb
  app/views/profile/_profile.html.erb
  app/views/profile/index.html.erb
  app/views/profile/orders/index.html.erb
  app/views/reviews/edit.html.erb
  app/views/sessions/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/features/merchants/index_spec.rb
Labels: refactor

#19 Add Model Tests
  spec/models/item_spec.rb
  spec/models/order_spec.rb
Labels: test-spec

#20 Method refactor
  app/controllers/item_orders_controller.rb
  app/controllers/items_controller.rb
  app/views/items/index.html.erb
Labels: refactor

#22 Review and refactor
  app/views/merchants/_merchants_index.html.erb
  spec/models/item_orders_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/order_spec.rb
  spec/models/user_spec.rb
Labels: refactor

#24 Misc. Updates
  app/assets/stylesheets/application.css
  app/controllers/cart_controller.rb
  app/controllers/item_orders_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/passwords_controller.rb
  app/controllers/sessions_controller.rb
  app/views/admin/dashboard/index.html.erb
  app/views/admin/profile/index.html.erb
  app/views/cart/show.html.erb
  app/views/items/index.html.erb
  app/views/merchant/items/index.html.erb
  app/views/profile/orders/index.html.erb
  db/seeds.rb
  spec/features/admin/orders/show_spec.rb
  spec/features/admin/profiles/index_spec.rb
  spec/features/cart/checkout_spec.rb
  spec/features/cart/show_spec.rb
  spec/features/orders/creation_spec.rb
  spec/features/orders/new_spec.rb
  spec/features/sessions/new_spec.rb
Labels: refactor
